### PR TITLE
27-category page frontend

### PR DESCRIPTION
**Pull request by mkb02**
Added an admin-specific page allowing users to view categories and their classification. The window allows for multiple pages with a given number of rows for each page. maxRowsPerPage is currently decided by the backend users.

Example view with maxRowsPerPage=1:
https://github.com/Hack4Impact-UMD/jefferson-area-board-for-aging/assets/110471343/2c7bea33-e911-40e9-8bc4-db3e096a7b6b

Example view with maxRowsPerPage=5:
https://github.com/Hack4Impact-UMD/jefferson-area-board-for-aging/assets/110471343/5d915580-9a40-40e0-a8f8-a72b76257f91

image

### CODE REVIEW

**Comment by RickyLi15** [comment]
Not sure why but this is what it looks like on my end: 
Screen Shot 2023-11-26 at 8 03 14 PM

**Comment by RickyLi15** [comment]
From the demo and the code, I don't see any major concerns. It's just that it appears differently for me for some reason.

**Comment by mkb02** [comment]
Hello, I think I fixed the problem, but am not sure. Could you check on your end?

**Review by RickyLi15 — APPROVED** [review]
It looks

**Pull request merged**
